apiVersion: v1
kind: Service
metadata:
  name: flask-config-service
spec:
  selector:
    app: flask-config
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort  # or LoadBalancer if using a cloud provider

